;;; decklet-backfill-test.el --- Tests for decklet-backfill -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)

(add-to-list 'load-path "/Users/yilinzhang/.emacs.d/site-lisp/decklet")
(add-to-list 'load-path "/Users/yilinzhang/.emacs.d/site-lisp/decklet-backfill")

(require 'decklet-backfill)

(ert-deftest decklet-backfill-prompt-includes-skill-and-format-hint ()
  (let ((decklet-backfill-output-format 'org))
    (cl-letf (((symbol-function 'decklet-backfill--skill-text)
               (lambda () "skill body")))
      (should (equal (decklet-backfill--prompt "pitch")
                     "skill body
----
pitch (org)
")))))

(ert-deftest decklet-backfill-prompt-with-output-file-mentions-path ()
  (cl-letf (((symbol-function 'decklet-backfill--prompt)
             (lambda (_word) "base prompt
")))
    (let ((prompt (decklet-backfill--prompt-with-output-file "pitch" "/tmp/result.org")))
      (should (string-match-p "base prompt" prompt))
      (should (string-match-p "/tmp/result\\.org" prompt))
      (should (string-match-p "Do not print the explanation to stdout" prompt)))))

(ert-deftest decklet-backfill-task-result-file-is-unique-per-word ()
  (let ((decklet-backfill-runtime-directory "/tmp/dbf-runtime/"))
    (should-not (equal (decklet-backfill--task-result-file "batch1" "pitch")
                       (decklet-backfill--task-result-file "batch1" "catechism")))))

(ert-deftest decklet-backfill-target-words-uses-marked-words-when-confirmed ()
  (with-temp-buffer
    (cl-letf (((symbol-function 'derived-mode-p)
               (lambda (mode) (eq mode 'decklet-edit-mode)))
              ((symbol-function 'decklet-edit--marked-words)
               (lambda () '("pitch" "catechism")))
              ((symbol-function 'yes-or-no-p)
               (lambda (_prompt) t)))
      (should (equal (decklet-backfill--target-words)
                     '("pitch" "catechism"))))))

(ert-deftest decklet-backfill-target-words-uses-single-marked-word-directly ()
  (with-temp-buffer
    (cl-letf (((symbol-function 'derived-mode-p)
               (lambda (mode) (eq mode 'decklet-edit-mode)))
              ((symbol-function 'decklet-edit--marked-words)
               (lambda () '("pitch"))))
      ;; Exactly one mark: use it directly without prompting.
      (should (equal (decklet-backfill--target-words) '("pitch"))))))

(ert-deftest decklet-backfill-target-words-cancels-when-user-declines-batch ()
  (with-temp-buffer
    (cl-letf (((symbol-function 'derived-mode-p)
               (lambda (mode) (eq mode 'decklet-edit-mode)))
              ((symbol-function 'decklet-edit--marked-words)
               (lambda () '("pitch" "catechism")))
              ((symbol-function 'yes-or-no-p)
               (lambda (_prompt) nil)))
      (should-error (decklet-backfill--target-words) :type 'user-error))))

(ert-deftest decklet-backfill-prepare-words-skips-existing-backs-when-not-overriding ()
  (cl-letf (((symbol-function 'decklet-backfill--existing-back)
             (lambda (word)
               (and (string= word "pitch") "existing back")))
            ((symbol-function 'yes-or-no-p)
             (lambda (_prompt) nil)))
    (should (equal (decklet-backfill--prepare-words '("pitch" "catechism"))
                   '("catechism")))))

(ert-deftest decklet-backfill-start-batch-creates-one-task-per-word ()
  (let (started-words)
    (cl-letf (((symbol-function 'decklet-backfill--ensure-idle) #'ignore)
              ((symbol-function 'decklet-backfill--ensure-runtime-directory) #'ignore)
              ((symbol-function 'decklet-backfill--start-task)
               (lambda (task _batch)
                 (push (decklet-backfill-task-word task) started-words)
                 task))
              ((symbol-function 'message) #'ignore))
      (let ((batch (decklet-backfill--start-batch '("pitch" "catechism"))))
        (should (= (length (decklet-backfill-batch-tasks batch)) 2))
        (should (equal (sort started-words #'string<)
                       '("catechism" "pitch")))))))

(ert-deftest decklet-backfill-start-task-uses-json-output-and_message_separator ()
  (let (captured)
    (cl-letf (((symbol-function 'start-process)
               (lambda (&rest args)
                 (setq captured args)
                 (make-process :name "dbf-start" :buffer (nth 1 args) :command '("cat"))))
              ((symbol-function 'set-process-query-on-exit-flag) #'ignore)
              ((symbol-function 'set-process-sentinel) #'ignore)
              ((symbol-function 'decklet-backfill--start-timeout) #'ignore)
              ((symbol-function 'process-put) (lambda (&rest _) nil))
              ((symbol-function 'decklet-backfill--clear-result-file) #'ignore))
      (let* ((task (decklet-backfill-task-create :word "pitch" :result-file "/tmp/pitch.org" :status 'pending))
             (batch (decklet-backfill-batch-create :id "batch" :tasks (list task))))
        (decklet-backfill--start-task task batch)
        (should (equal (seq-subseq captured 2 6)
                       (list decklet-backfill-opencode-command "run" "--format" "json")))
        (should (equal (nth 6 captured) "--"))))))

(ert-deftest decklet-backfill-start-batch-rejects-when-batch-active ()
  (let* ((task (decklet-backfill-task-create :status 'running))
         (decklet-backfill--active-batch
          (decklet-backfill-batch-create :id "busy" :tasks (list task))))
    (should-error (decklet-backfill--start-batch '("pitch")) :type 'user-error)))

(ert-deftest decklet-backfill-cancel-stops-running-and-pending-tasks ()
  (let* ((process-a (make-process :name "dbf-a" :buffer nil :command '("cat")))
         (task-a (decklet-backfill-task-create :word "pitch" :process process-a :status 'running))
         (task-b (decklet-backfill-task-create :word "catechism" :status 'pending))
         (decklet-backfill--active-batch
          (decklet-backfill-batch-create :id "batch" :tasks (list task-a task-b)))
         killed)
    (unwind-protect
        (cl-letf (((symbol-function 'delete-process)
                   (lambda (process) (push process killed))))
          (decklet-backfill-cancel)
          (should (equal killed (list process-a)))
          (should (eq (decklet-backfill-task-status task-a) 'cancelled))
          (should (eq (decklet-backfill-task-status task-b) 'cancelled)))
      (ignore-errors (delete-process process-a)))))

(ert-deftest decklet-backfill-timeout-only-affects-one-task ()
  (let* ((process-a (make-process :name "dbf-timeout-a" :buffer nil :command '("cat")))
         (process-b (make-process :name "dbf-timeout-b" :buffer nil :command '("cat")))
         (task-a (decklet-backfill-task-create :word "pitch" :process process-a :status 'running))
         (task-b (decklet-backfill-task-create :word "catechism" :process process-b :status 'running))
         (batch (decklet-backfill-batch-create :id "batch" :tasks (list task-a task-b)))
         (decklet-backfill--active-batch batch)
         (callback nil)
         (decklet-backfill-timeout-seconds 5)
         deleted)
    (unwind-protect
        (cl-letf (((symbol-function 'run-at-time)
                   (lambda (_secs _repeat fn)
                     (setq callback fn)
                     'fake-timer))
                  ((symbol-function 'process-live-p) (lambda (_proc) t))
                  ((symbol-function 'delete-process)
                   (lambda (process)
                     (setq deleted process))))
          (decklet-backfill--start-timeout task-a batch)
          (funcall callback)
          (should (eq deleted process-a))
          (should (eq (decklet-backfill-task-status task-a) 'timed-out))
          (should (eq (decklet-backfill-task-status task-b) 'running)))
      (ignore-errors (delete-process process-a))
      (ignore-errors (delete-process process-b)))))

(ert-deftest decklet-backfill-process-sentinel-uses-original-word ()
  (let* ((process (make-process :name "dbf-sentinel" :buffer (generate-new-buffer " *dbf* ") :command '("cat")))
         (task (decklet-backfill-task-create :word "pitch" :process process :result-file "/tmp/result.org" :status 'running))
         (batch (decklet-backfill-batch-create :id "batch" :tasks (list task)))
         (decklet-current-word "different-word")
         saved-word)
    (unwind-protect
        (progn
          (set-process-query-on-exit-flag process nil)
          (process-put process :decklet-task task)
          (process-put process :decklet-batch batch)
          (setq decklet-backfill--active-batch batch)
          (cl-letf (((symbol-function 'process-status) (lambda (_proc) 'exit))
                    ((symbol-function 'process-exit-status) (lambda (_proc) 0))
                    ((symbol-function 'decklet-backfill--save-file-to-card-back)
                     (lambda (word _path) (setq saved-word word)))
                    ((symbol-function 'message) #'ignore)
                    ((symbol-function 'kill-buffer) #'ignore))
            (decklet-backfill--process-sentinel process nil)
            (should (equal saved-word "pitch"))))
      (ignore-errors (delete-process process))
      (when (buffer-live-p (process-buffer process))
        (kill-buffer (process-buffer process)))
      (setq decklet-backfill--active-batch nil))))

(ert-deftest decklet-backfill-extract-session-id-from-json-buffer ()
  (with-temp-buffer
    (insert "{\"type\":\"text\",\"sessionID\":\"ses_1\"}\n")
    (insert "{\"type\":\"tool_use\",\"sessionID\":\"ses_2\"}\n")
    (should (equal (decklet-backfill--extract-session-id (current-buffer)) "ses_2"))))

(ert-deftest decklet-backfill-sentinel-triggers-session-cleanup ()
  (let* ((buffer (generate-new-buffer " *dbf-cleanup* "))
         (process (make-process :name "dbf-sentinel-cleanup" :buffer buffer :command '("cat")))
         (task (decklet-backfill-task-create :word "pitch" :process process :result-file "/tmp/result.org" :status 'running))
         (batch (decklet-backfill-batch-create :id "batch" :tasks (list task)))
         cleaned-session)
    (unwind-protect
        (progn
          (with-current-buffer buffer
            (insert "{\"type\":\"text\",\"sessionID\":\"ses_cleanup\"}\n"))
          (process-put process :decklet-task task)
          (process-put process :decklet-batch batch)
          (setq decklet-backfill--active-batch batch)
          (cl-letf (((symbol-function 'process-status) (lambda (_proc) 'exit))
                    ((symbol-function 'process-exit-status) (lambda (_proc) 0))
                    ((symbol-function 'decklet-backfill--save-file-to-card-back) (lambda (&rest _) nil))
                    ((symbol-function 'message) #'ignore)
                    ((symbol-function 'kill-buffer) #'ignore)
                    ((symbol-function 'decklet-backfill--cleanup-session)
                     (lambda (cleanup-task)
                       (setq cleaned-session (decklet-backfill-task-session-id cleanup-task)))))
            (decklet-backfill--process-sentinel process nil)
            (should (equal cleaned-session "ses_cleanup"))))
      (ignore-errors (delete-process process))
      (when (buffer-live-p buffer)
        (kill-buffer buffer))
      (setq decklet-backfill--active-batch nil))))

(ert-deftest decklet-backfill-finish-batch-clears-active-and-shows-summary ()
  (let* ((task-a (decklet-backfill-task-create :status 'success))
         (task-b (decklet-backfill-task-create :status 'failed))
         (batch (decklet-backfill-batch-create :id "batch" :tasks (list task-a task-b)))
         (summary-shown nil))
    (setq decklet-backfill--active-batch batch)
    (cl-letf (((symbol-function 'message)
               (lambda (fmt &rest args)
                 (when (string-match-p "finished" (apply #'format fmt args))
                   (setq summary-shown t)))))
      (decklet-backfill--finish-batch-if-done batch)
      (should summary-shown)
      (should-not decklet-backfill--active-batch))))

(ert-deftest decklet-backfill-batch-summary-counts-are-correct ()
  (let* ((task-success  (decklet-backfill-task-create :status 'success))
         (task-failed   (decklet-backfill-task-create :status 'failed))
         (task-cancelled (decklet-backfill-task-create :status 'cancelled))
         (task-timed-out (decklet-backfill-task-create :status 'timed-out))
         (batch (decklet-backfill-batch-create
                 :id "batch"
                 :tasks (list task-success task-failed task-cancelled task-timed-out)))
         (summary (decklet-backfill--batch-summary batch)))
    (should (string-match-p "1 succeeded" summary))
    (should (string-match-p "1 failed" summary))
    (should (string-match-p "1 cancelled" summary))
    (should (string-match-p "1 timed out" summary))))

(ert-deftest decklet-backfill-finish-batch-suppresses-summary-for-single-word ()
  (let* ((task (decklet-backfill-task-create :status 'success))
         (batch (decklet-backfill-batch-create :id "batch" :tasks (list task)))
         (summary-shown nil))
    (setq decklet-backfill--active-batch batch)
    (cl-letf (((symbol-function 'message)
               (lambda (fmt &rest args)
                 (when (string-match-p "finished" (apply #'format fmt args))
                   (setq summary-shown t)))))
      (decklet-backfill--finish-batch-if-done batch)
      (should-not summary-shown)
      (should-not decklet-backfill--active-batch))))

(ert-deftest decklet-backfill-start-task-clears-result-file-before-process ()
  (let (clear-called process-called)
    (cl-letf (((symbol-function 'decklet-backfill--clear-result-file)
               (lambda (_path)
                 (should-not process-called)
                 (setq clear-called t)))
              ((symbol-function 'start-process)
               (lambda (&rest args)
                 (setq process-called t)
                 (make-process :name "dbf-order" :buffer (nth 1 args) :command '("cat"))))
              ((symbol-function 'set-process-query-on-exit-flag) #'ignore)
              ((symbol-function 'set-process-sentinel) #'ignore)
              ((symbol-function 'decklet-backfill--start-timeout) #'ignore)
              ((symbol-function 'process-put) (lambda (&rest _) nil)))
      (let* ((task (decklet-backfill-task-create :word "pitch" :result-file "/tmp/pitch.org" :status 'pending))
             (batch (decklet-backfill-batch-create :id "batch" :tasks (list task))))
        (decklet-backfill--start-task task batch)
        (should clear-called)
        (should process-called)))))

(ert-deftest decklet-backfill-save-file-to-card-back-updates-db ()
  (let ((temp-file (make-temp-file "decklet-backfill-test-" nil ".org")))
    (unwind-protect
        (progn
          (with-temp-file temp-file
            (insert "generated explanation"))
          (cl-letf (((symbol-function 'decklet-set-card-back)
                     (lambda (word back)
                       (should (equal word "pitch"))
                       (should (equal back "generated explanation")))))
            (decklet-backfill--save-file-to-card-back "pitch" temp-file)))
      (delete-file temp-file))))

(ert-deftest decklet-backfill-start-batch-respects-concurrency-limit ()
  (let ((decklet-backfill-max-concurrent-tasks 2)
        started-words)
    (cl-letf (((symbol-function 'decklet-backfill--ensure-idle) #'ignore)
              ((symbol-function 'decklet-backfill--ensure-runtime-directory) #'ignore)
              ((symbol-function 'decklet-backfill--start-task)
               (lambda (task _batch)
                 (push (decklet-backfill-task-word task) started-words)
                 task))
              ((symbol-function 'message) #'ignore))
      (let ((batch (decklet-backfill--start-batch '("a" "b" "c" "d"))))
        ;; All 4 tasks exist in the batch.
        (should (= (length (decklet-backfill-batch-tasks batch)) 4))
        ;; Only the first 2 were actually started.
        (should (= (length started-words) 2))))))

(ert-deftest decklet-backfill-maybe-start-next-task-starts-pending ()
  (let* ((task-done    (decklet-backfill-task-create :word "a" :status 'success))
         (task-pending (decklet-backfill-task-create :word "b" :status 'pending))
         (batch (decklet-backfill-batch-create :id "batch" :tasks (list task-done task-pending)))
         (decklet-backfill--active-batch batch)
         (decklet-backfill-max-concurrent-tasks 1)
         started)
    (cl-letf (((symbol-function 'decklet-backfill--start-task)
               (lambda (task _batch)
                 (push (decklet-backfill-task-word task) started)
                 task)))
      (decklet-backfill--maybe-start-next-task batch)
      (should (equal started '("b"))))))

(ert-deftest decklet-backfill-maybe-start-next-task-respects-limit ()
  (let* ((task-running (decklet-backfill-task-create :word "a" :status 'running))
         (task-pending (decklet-backfill-task-create :word "b" :status 'pending))
         (batch (decklet-backfill-batch-create :id "batch" :tasks (list task-running task-pending)))
         (decklet-backfill--active-batch batch)
         (decklet-backfill-max-concurrent-tasks 1)
         started)
    (cl-letf (((symbol-function 'decklet-backfill--start-task)
               (lambda (task _batch)
                 (push (decklet-backfill-task-word task) started)
                 task)))
      (decklet-backfill--maybe-start-next-task batch)
      ;; Already at the limit; nothing should start.
      (should (null started)))))

(ert-deftest decklet-backfill-sentinel-shows-progress-for-batch ()
  (let* ((process (make-process :name "dbf-prog" :buffer (generate-new-buffer " *dbf-prog*") :command '("cat")))
         (task-a (decklet-backfill-task-create :word "pitch" :process process
                                               :result-file "/tmp/pitch.org" :status 'running))
         (task-b (decklet-backfill-task-create :word "catechism" :status 'success))
         (batch (decklet-backfill-batch-create :id "batch" :tasks (list task-a task-b)))
         (decklet-backfill--active-batch batch)
         last-message)
    (unwind-protect
        (progn
          (process-put process :decklet-task task-a)
          (process-put process :decklet-batch batch)
          (set-process-query-on-exit-flag process nil)
          (cl-letf (((symbol-function 'process-status) (lambda (_p) 'exit))
                    ((symbol-function 'process-exit-status) (lambda (_p) 0))
                    ((symbol-function 'decklet-backfill--save-file-to-card-back) #'ignore)
                    ((symbol-function 'decklet-backfill--cleanup-session) #'ignore)
                    ((symbol-function 'decklet-backfill--maybe-start-next-task) #'ignore)
                    ((symbol-function 'decklet-backfill--finish-batch-if-done) #'ignore)
                    ((symbol-function 'kill-buffer) #'ignore)
                    ((symbol-function 'message)
                     (lambda (fmt &rest args) (setq last-message (apply #'format fmt args)))))
            (decklet-backfill--process-sentinel process nil)
            ;; Progress message should include quoted word and [N/total].
            (should (string-match-p "\"pitch\"" last-message))
            (should (string-match-p "\\[2/2\\]" last-message))))
      (ignore-errors (delete-process process))
      (when (buffer-live-p (process-buffer process))
        (kill-buffer (process-buffer process)))
      (setq decklet-backfill--active-batch nil))))

(ert-deftest decklet-backfill-batch-done-count ()
  (let* ((tasks (list (decklet-backfill-task-create :status 'success)
                      (decklet-backfill-task-create :status 'failed)
                      (decklet-backfill-task-create :status 'running)
                      (decklet-backfill-task-create :status 'pending)))
         (batch (decklet-backfill-batch-create :id "batch" :tasks tasks)))
    (should (= (decklet-backfill--batch-done-count batch) 2))))

(provide 'decklet-backfill-test)

;;; decklet-backfill-test.el ends here
